---
dhcp_server: "10.1.0.2"

svi_interfaces:
  - name: vlan99
    ip_address: 10.1.0.3/24
  - name: vlan10
    ip_address: 10.1.1.31/24
  - name: vlan20
    ip_address: 10.1.2.32/24
  - name: vlan30
    ip_address: 10.1.3.33/24
  - name: vlan40
    ip_address: 10.1.4.34/24

access_ports:
  - name: Ethernet4
    vlan: 99

trunk_ports:
  - name: Ethernet1
    allowed_vlans:
      - "10"
      - "20"
      - "30"
  - name: Ethernet2
    allowed_vlans:
      - "20"
      - "30"
  - name: Ethernet3
    allowed_vlans:
      - "10"
      - "20"
      - "40"
