all:
  vars:
    # The generated inventory is assumed to be used from the clab host.
    # Hence no http proxy should be used. Therefore we make sure the http
    # module does not attempt using any global http proxy.
    ansible_httpapi_use_proxy: false
  children:
    arista_ceos:
      vars:
        # ansible_connection: set ansible_connection variable if required
        ansible_user: admin
        ansible_password: admin
      children:
        sw-distribution:
          hosts:
            clab-remote_dhcp_automation-sw-distribution-1:
              ansible_host: 172.20.20.16
        sw-access:
          hosts:
            clab-remote_dhcp_automation-sw-access-1:
              ansible_host: 172.20.20.34
            clab-remote_dhcp_automation-sw-access-2:
              ansible_host: 172.20.20.21
            clab-remote_dhcp_automation-sw-access-3:
              ansible_host: 172.20.20.24
    linux:
      vars:
        ansible_user: admin
        ansible_password: multit00l
      hosts:
        clab-remote_dhcp_automation-client-01:
          ansible_host: 172.20.20.2
        clab-remote_dhcp_automation-client-02:
          ansible_host: 172.20.20.25
        clab-remote_dhcp_automation-client-03:
          ansible_host: 172.20.20.22
        clab-remote_dhcp_automation-client-04:
          ansible_host: 172.20.20.31
        clab-remote_dhcp_automation-client-05:
          ansible_host: 172.20.20.11
        clab-remote_dhcp_automation-client-06:
          ansible_host: 172.20.20.33
        clab-remote_dhcp_automation-client-07:
          ansible_host: 172.20.20.20
        clab-remote_dhcp_automation-client-08:
          ansible_host: 172.20.20.27
        clab-remote_dhcp_automation-client-09:
          ansible_host: 172.20.20.3
        clab-remote_dhcp_automation-dhcp-server:
          ansible_host: 172.20.20.32

